### PR TITLE
update filters with latest Grid Map Filters.

### PR DESCRIPTION
**Pull request by marco-tranzatto**
Update needed after replacment of filter `gridMapFilters/WeightedSumFilter` with `gridMapFilters/MathExpressionFilter` in Grid Map repo.

See https://github.com/ethz-asl/grid_map/pull/120

### CODE REVIEW

**Comment by marco-tranzatto** [comment]
@pfankhauser I did not do that because I thought It'd be strange to still have the source file of SurfaceNormalsFilter.cpp but using a Grid Map filter.

What about if I replace surfaceNormalFilter and we deprecate https://github.com/ethz-asl/traversability_estimation/blob/master/traversability_estimation_filters/src/SurfaceNormalsFilter.cpp ?
If so, what's the best way?

**Comment by pfankhauser** [comment]
Yes, that's the idea. Delete the surface normal filter from traversability estimation and make it use the one from grid map instead.

**Comment by marco-tranzatto** [comment]
@pfankhauser I didn't get that you wanted to delete the Filter in this repo. I've just done it and updated `robot_filter_parameter.yaml`. If that's ok with you I'd merge these changes.

**Comment by pfankhauser** [comment]
👍

**Pull request merged**
